version: "3.3"
volumes:
  db:
    driver:
      local
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: instragram
    container_name: instragram
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - instragram-network

#  db:
#    image: mysql:8
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
#    networks:
#      - instragram-network
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: instragram
      MYSQL_ROOT_PASSWORD: nishpa
      MYSQL_PASSWORD: nishpa
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - instragram-network

  nginx:
    image: nginx:alpine
    container_name: instragram-nginx
    restart: unless-stopped
    ports:
      - 443:80
    volumes:
      - ./:/var/www
      - ./touch.conf:/etc/nginx/conf.d/default.conf
    networks:
      - instragram-network

networks:
  instragram-network:
    driver: bridge
